name: Echo Time and Inputs

on:
  workflow_dispatch:
    inputs:
      manually_insert:
        description: "Bypassing HubSpot: Create a new tenant provisioning manually?"
        type: choice
        options:
          - no
          - yes
        required: true
      tenant_name:
        description: "Tenant name"
        type: string
        required: false
      poc_date:
        description: "POC Date: format should be yyyy-mm-dd, tenant will be provisioned once the poc date is in the upcoming 7 days"
        type: string
        required: false

jobs:
  echo_time_job:
    runs-on: ubuntu-latest

    steps:
      - name: Echo formatted time
        run: |
          echo "Manually Insert: ${{ github.event.inputs.manually_insert }}"
          echo "Tenant Name: ${{ github.event.inputs.tenant_name }}"
          echo "POC Date: ${{ github.event.inputs.poc_date }}"
