name: Echo Time

on:
  workflow_dispatch:

jobs:
  echo_time_job:
    runs-on: ubuntu-latest

    steps:
      - name: Echo formatted time
        run: |
          current_time=$(date +"%Y-%m-%d")
          echo "Formatted Time: $current_time"
