name: Echo Time

on:
  workflow_dispatch:

jobs:
  echo_time_job:
    runs-on: ubuntu-latest

    steps:
      - name: Echo formatted time
        run: |
          current_time=$(date +"%Y-%m-%d")
          formatted_time=$(echo $current_time | sed 's/-//g' | sed 's/^\(....\)\(..\)\(..\)$/\1\2-\3/')
          echo "Formatted Time: $formatted_time"
