name: Triggered Workflow

on:
  workflow_dispatch:

jobs:
  triggered_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run triggered action
        run: echo "Workflow triggered from Zapier!"
