name: Primary Workflow

on:
  workflow_dispatch:
    inputs:
      customer_full_name:
        description: "Customer full name"
        type: string
        required: true
      email:
        description: "Email"
        type: string
        required: true
      image_deployment_type:
        description: "Customer image deployment type"
        type: string
        required: true
      customer_public_facing_ips:
        description: "Customer public facing IPs"
        type: string
        required: true
      mssp_access:
        description: "MSSP access"
        type: string
        required: true

jobs:
  triggered_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run triggered action
        run: |
          echo "Workflow triggered from Zapier!"
          echo "Customer Full Name: ${{ github.event.inputs.customer_full_name }}"
          echo "Email: ${{ github.event.inputs.email }}"
          echo "Image Deployment Type: ${{ github.event.inputs.image_deployment_type }}"
          echo "Customer Public Facing IPs: ${{ github.event.inputs.customer_public_facing_ips }}"
          echo "MSSP Access: ${{ github.event.inputs.mssp_access }}"

      - name: Calculate POC Date
        id: poc_date
        run: |
          poc_date=$(date +"%Y-%m-%d")
          echo "::set-output name=date::$poc_date"

  trigger_echo_time:
    runs-on: ubuntu-latest
    needs: triggered_job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger Echo Time Workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/benos-veriti/github-action-webhook/actions/workflows/echo-time.yaml/dispatches \
            -d '{
                  "ref": "main",
                  "inputs": {
                    "manually_insert": "yes",  # Ensure this matches the allowed options
                    "tenant_name": "${{ github.event.inputs.customer_full_name }}",
                    "poc_date": "${{ needs.triggered_job.outputs.date }}"
                  }
                }'